run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    
  govet:
    enable-all: false
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - composites
      - copylocks
      - errorsas
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unusedresult

  gofmt:
    simplify: true

  goimports:
    local-prefixes: quest-manager

  gocyclo:
    min-complexity: 20

  dupl:
    threshold: 150

  goconst:
    min-len: 3
    min-occurrences: 5

  misspell:
    locale: US

  lll:
    line-length: 150

  unused:
    check-exported: false

  unparam:
    check-exported: false

  nakedret:
    max-func-lines: 50

linters:
  disable-all: true
  enable:
    # Основные критичные линтеры
    - errcheck
    - govet  
    - staticcheck
    - unused
    - typecheck
    - ineffassign
    - gofmt
    - goimports
    - gosimple
    
    # Менее критичные (но полезные)
    - misspell
    - unconvert
    - whitespace

issues:
  exclude-rules:
    # Исключения для тестовых файлов
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - dupl
        - lll

    # Исключения для main.go
    - path: cmd/app/main\.go
      linters:
        - errcheck

    # Исключения для generated кода
    - path: internal/generated/
      linters:
        - gosec
        - errcheck
        - goconst
        - dupl
        - lll

    # Исключения для моков и тестовых утилит
    - path: tests/
      linters:
        - unused
        - errcheck

    # Исключения для cmd/ пакета
    - path: cmd/
      linters:
        - errcheck

  exclude:
    # Стандартные исключения
    - 'Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|fmt\.Print.*|os\.(Un)?Setenv). is not checked'
    - 'func name will be used as test\.Test.* by other packages, and that stutters; consider calling this'
    - 'G104: Errors unhandled'
    - 'Error return value of .*\.Log.* is not checked'
    - 'Error return value of .*Rollback.* is not checked'

  max-issues-per-linter: 50
  max-same-issues: 10